name: synth_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - portaudio
  - numpy
  - pandas
  - pip
  - matplotlib
  - ipykernel
  - scikit-learn
  - libsndfile
  - ffmpeg
  - pip:
    - pyo
    - torch
    - torchaudio
    - torchvision
    - torchsummary
    - torchcodec
